package platform

import "github.com/sarpt/gamedbv/pkg/gamedbv"

// DefaultConfigsPerPlatform are default configuration values used for platforms database files when no overwrites are present
var DefaultConfigsPerPlatform = map[string]Config{
	Wii: Config{
		appConfig:         gamedbv.DefaultConfig,
		archiveFileName:   "wiidb.zip",
		contentFileName:   "wiitdb.xml",
		databaseType:      "GameTDB",
		docType:           "gametdb/game",
		url:               "https://www.gametdb.com/wiitdb.zip",
		forceDbDownload:   false,
		indexType:         "bleve",
		IndexDir:          "wii_bleve",
		platformDirectory: "wii",
		platformName:      Wii,
	},
	Ps3: Config{
		appConfig:         gamedbv.DefaultConfig,
		archiveFileName:   "ps3db.zip",
		contentFileName:   "ps3tdb.xml",
		databaseType:      "GameTDB",
		docType:           "gametdb/game",
		url:               "https://www.gametdb.com/ps3tdb.zip",
		forceDbDownload:   false,
		indexType:         "bleve",
		IndexDir:          "ps3_bleve",
		platformDirectory: "ps3",
		platformName:      Ps3,
	},
	Wiiu: Config{
		appConfig:         gamedbv.DefaultConfig,
		archiveFileName:   "wiiu.zip",
		contentFileName:   "wiiutdb.xml",
		databaseType:      "GameTDB",
		docType:           "gametdb/game",
		url:               "https://www.gametdb.com/wiiutdb.zip",
		forceDbDownload:   false,
		indexType:         "bleve",
		IndexDir:          "wiiu_bleve",
		platformDirectory: "wiiu",
		platformName:      Wiiu,
	},
	Nds: Config{
		appConfig:         gamedbv.DefaultConfig,
		archiveFileName:   "nds.zip",
		contentFileName:   "dstdb.xml",
		databaseType:      "GameTDB",
		docType:           "gametdb/game",
		url:               "https://www.gametdb.com/dstdb.zip",
		forceDbDownload:   false,
		indexType:         "bleve",
		IndexDir:          "nds_bleve",
		platformDirectory: "nds",
		platformName:      Nds,
	},
	N3ds: Config{
		appConfig:         gamedbv.DefaultConfig,
		archiveFileName:   "3ds.zip",
		contentFileName:   "3dstdb.xml",
		databaseType:      "GameTDB",
		docType:           "gametdb/game",
		url:               "https://www.gametdb.com/3dstdb.zip",
		forceDbDownload:   false,
		indexType:         "bleve",
		IndexDir:          "3ds_bleve",
		platformDirectory: "3ds",
		platformName:      N3ds,
	},
	Switch: Config{
		appConfig:         gamedbv.DefaultConfig,
		archiveFileName:   "switch.zip",
		contentFileName:   "switchtdb.xml",
		databaseType:      "GameTDB",
		docType:           "gametdb/game",
		url:               "https://www.gametdb.com/switchtdb.zip",
		forceDbDownload:   false,
		indexType:         "bleve",
		IndexDir:          "switch_bleve",
		platformDirectory: "switch",
		platformName:      Switch,
	},
}
