// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: dl/dl.proto

package dl

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PlatformsDownloadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platforms []string `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
}

func (x *PlatformsDownloadReq) Reset() {
	*x = PlatformsDownloadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dl_dl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformsDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformsDownloadReq) ProtoMessage() {}

func (x *PlatformsDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_dl_dl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformsDownloadReq.ProtoReflect.Descriptor instead.
func (*PlatformsDownloadReq) Descriptor() ([]byte, []int) {
	return file_dl_dl_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformsDownloadReq) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type PlatformsDownloadStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Process  string `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	Step     string `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PlatformsDownloadStatus) Reset() {
	*x = PlatformsDownloadStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dl_dl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformsDownloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformsDownloadStatus) ProtoMessage() {}

func (x *PlatformsDownloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dl_dl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformsDownloadStatus.ProtoReflect.Descriptor instead.
func (*PlatformsDownloadStatus) Descriptor() ([]byte, []int) {
	return file_dl_dl_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformsDownloadStatus) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformsDownloadStatus) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *PlatformsDownloadStatus) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *PlatformsDownloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dl_dl_proto protoreflect.FileDescriptor

var file_dl_dl_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x6c, 0x2f, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a,
	0x14, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x73, 0x22, 0x7d, 0x0a, 0x17, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x4e, 0x0a, 0x02, 0x44, 0x6c, 0x12, 0x48, 0x0a, 0x11, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x12, 0x15, 0x2e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x61, 0x72, 0x70, 0x74, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x64, 0x62, 0x76, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dl_dl_proto_rawDescOnce sync.Once
	file_dl_dl_proto_rawDescData = file_dl_dl_proto_rawDesc
)

func file_dl_dl_proto_rawDescGZIP() []byte {
	file_dl_dl_proto_rawDescOnce.Do(func() {
		file_dl_dl_proto_rawDescData = protoimpl.X.CompressGZIP(file_dl_dl_proto_rawDescData)
	})
	return file_dl_dl_proto_rawDescData
}

var file_dl_dl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dl_dl_proto_goTypes = []interface{}{
	(*PlatformsDownloadReq)(nil),    // 0: PlatformsDownloadReq
	(*PlatformsDownloadStatus)(nil), // 1: PlatformsDownloadStatus
}
var file_dl_dl_proto_depIdxs = []int32{
	0, // 0: Dl.DownloadPlatforms:input_type -> PlatformsDownloadReq
	1, // 1: Dl.DownloadPlatforms:output_type -> PlatformsDownloadStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dl_dl_proto_init() }
func file_dl_dl_proto_init() {
	if File_dl_dl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dl_dl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformsDownloadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dl_dl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformsDownloadStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dl_dl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dl_dl_proto_goTypes,
		DependencyIndexes: file_dl_dl_proto_depIdxs,
		MessageInfos:      file_dl_dl_proto_msgTypes,
	}.Build()
	File_dl_dl_proto = out.File
	file_dl_dl_proto_rawDesc = nil
	file_dl_dl_proto_goTypes = nil
	file_dl_dl_proto_depIdxs = nil
}
